--- 
  # Messages (multi-langauge support)
  en:
    adding: "Adding"
    subtracting: "Subtracting"
    multiplying: "Multiplying"
    dividing: "Dividing"
    
    welcome: "Welcome to Calculator! Please enter your name:"
    greeting: "Hi"
    valid_name: "Make sure to use a valid name."
    
    first_number: "What's the first number?"
    second_number: "What's the second number?"
    invalid_number: "Hmm... that doesn't look like a valid number"
    
    operation: "What operation would you like to perform?"
    add: "1) add"
    subtract: "2) subtract"
    multiply: "3) multiply"
    divide: "4) divide"
    
    must_choose: "Must choose 1, 2, 3, or 4"
    two_numbers: "the two numbers..."

    result: "The result is"
    another_calc?: "Do you want to perform another calculation? (Y to calculate again)"
    thank_you: "Thank you for using the calculator. Good bye!"

  es: 
    adding: "agregando"
    subtracting: "Restar"
    multiplying: "multiplicando"
    dividing: "Divisor"
    
    welcome: "¡Bienvenido a Calculadora! Por favor, escriba su nombre:"
    greeting: "Hola"
    valid_name: "Asegúrese de utilizar un nombre válido."
  
    first_number: "¿Cuál es el primer número?"
    second_number: "¿Cuál es el segundo número?"
    invalid_number: "Hmm... eso no parece un número válido"
  
    operation: "¿Qué operación le gustaría realizar?"
    add: "1) agregar"
    subtract: "2) sustraer"
    multiply: "3) multiplicar"
    divide: "4) dividir"
  
    must_choose: "Debe elegir 1, 2, 3 o 4"
    two_numbers: "los dos numeros..."

    result: "El resultado es"
    another_calc?: "¿Desea realizar otro cálculo? (Y para calcular de nuevo)"
    thank_you: "Gracias por usar la calculadora. ¡Adiós!"
  
  