--- 
# English
en: {
  welcome_msg: "Welcome to Calculator! Please enter your name:",
  valid_name: "Make sure to use a valid name.",
  first_number: "What's the first number?",
  second_number: "What's the second number?",
  invalid_number: "Hmm... that doesn't look like a valid number"
}


